version: '3'

services:
  web:
    build: .
    container_name:  freeschema_based_fastapi_web
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app
    # extra_hosts:
    #   - "apischema.freeschema.com:127.0.0.1"
      